let x = 5;
let square_of_x = Math.pow(x, 2);
console.log(square_of_x);
console.log(Math.PI);
console.log(Math.sqrt(36));
console.log(Math.round(5.4));
console.log(Math.round(5.6));
console.log(Math.floor(5.9));
console.log(Math.ceil(5.2));
console.log(Math.min(1,-1,4,3.-0.2,-9,9));
console.log(Math.random());